### PR TITLE
2019 03 new metrics

### PR DESCRIPTION
**Pull request by Alb0t**
Sorting existing namespace metrics, adding some missing ones.
I really would like to add write_q, defrag_q, and shadow_write_q, but it doesn't look as simple as I had hoped. @alicebob do you think you can help with this? :)

ex...
```$ asinfo -lv 'namespace/ttd-coldstorage'|grep _q
storage-engine.device[0].write_q=344
storage-engine.device[0].defrag_q=3235
storage-engine.device[0].shadow_write_q=0
storage-engine.device[1].write_q=342
storage-engine.device[1].defrag_q=4313
storage-engine.device[1].shadow_write_q=0
storage-engine.device[2].write_q=908
storage-engine.device[2].defrag_q=14368
storage-engine.device[2].shadow_write_q=0
storage-engine.device[3].write_q=633
storage-engine.device[3].defrag_q=13717
storage-engine.device[3].shadow_write_q=0
storage-engine.device[4].write_q=17
storage-engine.device[4].defrag_q=3341
storage-engine.device[4].shadow_write_q=0
storage-engine.device[5].write_q=11
storage-engine.device[5].defrag_q=2708
storage-engine.device[5].shadow_write_q=0
storage-engine.device[6].write_q=4
storage-engine.device[6].defrag_q=4461
storage-engine.device[6].shadow_write_q=0
storage-engine.device[7].write_q=56
storage-engine.device[7].defrag_q=4524
storage-engine.device[7].shadow_write_q=0
```

### CODE REVIEW

**Comment by alicebob** [comment]
Thanks for the update! Merged.

What kind of metrics would you like to see for those "array" counters? Which dimensions?

**Comment by Alb0t** [comment]
They're actually gauges of the current queue. We need all of that in prometheus to alert off of. 
I would imagine we want, say this line `storage-engine.device[7].defrag_q=4524` to be searchable from prom as 
`aerospike_ns_defrag_q{device="7"}` maybe? for my use case, the devices are practically in random order so its not as valuable as just collecting all the different queue's and making sure they're not growing too high.

also defrag_q/write_q/shadow_q is also present on `files` which looks like this
```storage-engine.file[0].write_q=0
storage-engine.file[0].shadow_write_q=0```

**Comment by Alb0t** [comment]
@alicebob is this something you can help with? I might be able to figure it out, but I don't know go at all so its all foreign to me.. so curious if I should start hacking away or if you're working on it 🤞

**Comment by alicebob** [comment]
> @alicebob is this something you can help with? I might be able to figure it out, but I don't know go at all so its all foreign to me

Hi,

I had a look a while ago, but I didn't see an obvious way to solve it. It
already started with how to list one of these array metrics in the list with
metrics. If you have a nice suggestion how to do that... :)

But I'll continue again another day in any case.

**Pull request merged**
