### PR TITLE
additional metrics for device

### PR DESCRIPTION
**Pull request by toughrogrammer**

### CODE REVIEW

**Comment by alicebob** [comment]
Thanks for the PR! Which `asinfo` command shows those metrics?

**Comment by toughrogrammer** [comment]
You can test with `asinfo -l -v namespace/${your-namespace} | grep device`

**Comment by alicebob** [comment]
I don't have any: `asinfo -l -v namespace/test|grep dev`. That's on `Aerospike Community Edition build 3.15.1.4`

**Comment by alicebob** [comment]
Ah wait, maybe it needs an on-disk namespace?

**Comment by toughrogrammer** [comment]
Ah, maybe it's enterprise only metrics. I'm using aerospike with block storage engine, so I can watch disk usage with aerospike statistics only. It's aerospike-server-enterprise-3.15.1.4-ubuntu14.04.

**Comment by alicebob** [comment]
I happened to run `asinfo -l -v namespace/test`, which is an in-memory namespace, so it doesn't have the metrics. Running it against a disk based namespace does indeed give the stats. Nice find, thanks!

**Comment by alicebob** [comment]
published as https://github.com/alicebob/asprom/releases/tag/1.2.1

**Pull request merged**
