### PR TITLE
XDR] Adding metrics for digestlog

### PR DESCRIPTION
**Pull request by Xaelias**

### CODE REVIEW

**Comment by Xaelias** [comment]
```curl -s localhost:9146/metrics | grep dlog
# HELP aerospike_node_dlog_free_pct dlog free pct
# TYPE aerospike_node_dlog_free_pct gauge
aerospike_node_dlog_free_pct 100
# HELP aerospike_node_dlog_logged dlog logged
# TYPE aerospike_node_dlog_logged counter
aerospike_node_dlog_logged 8.480683761e+09
# HELP aerospike_node_dlog_overwritten_error dlog overwritten error
# TYPE aerospike_node_dlog_overwritten_error counter
aerospike_node_dlog_overwritten_error 6.65661e+08
# HELP aerospike_node_dlog_processed_link_down dlog processed link down
# TYPE aerospike_node_dlog_processed_link_down counter
aerospike_node_dlog_processed_link_down 0
# HELP aerospike_node_dlog_processed_main dlog processed main
# TYPE aerospike_node_dlog_processed_main counter
aerospike_node_dlog_processed_main 7.815685261e+09
# HELP aerospike_node_dlog_processed_replica dlog processed replica
# TYPE aerospike_node_dlog_processed_replica counter
aerospike_node_dlog_processed_replica 0
# HELP aerospike_node_dlog_relogged dlog relogged
# TYPE aerospike_node_dlog_relogged counter
aerospike_node_dlog_relogged 185829
# HELP aerospike_node_dlog_used_objects dlog used objects
# TYPE aerospike_node_dlog_used_objects counter
aerospike_node_dlog_used_objects 6.178461e+06```

**Comment by alicebob** [comment]
That seems to be related to XDR (cross datacenter foobar), which I don't have access to So, good to go :)

**Comment by alicebob** [comment]
(oops, wanted to merge)

**Comment by alicebob** [comment]
Released as https://github.com/alicebob/asprom/releases/tag/1.3.1

Thanks!

**Comment by alicebob** [comment]
Thanks!

**Pull request merged**
